apiVersion: apps/v1
kind: Deployment
metadata:
  name: djano-demo-deployment
  labels:
    app: djano-demo
spec:
  selector:
    matchLabels:
      app: dejango-demo
  template:
    metadata:
      labels:
        app: django-demo
    spec:
      containers:
      - name: django-demo
        image: django-demo
        ports:
        - containerPort: 8000
--
apiVersion: v1
kind: Service
metadata:
  name: djano-demo-service
spec:
  selector:
    app.kubernetes.io/name: django-demo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
